{
  # Task Config
  do_train: true,
  do_test: false,
  output_dir: ../models,

  # Data Config   
  data_dir: ../data,
  train_file: train_edited.csv,
  num_workers: 4,

  # Model Config
  architecture: Unet,
  encoder_name: efficientnet-b1,
  encoder_weights: imagenet,
  classes: 1,
  activation: sigmoid,

  # Train Config
  epochs: 50,
  batch_size: 8,
  accumulation_steps: 4,
  verbose: true,

  losses: DiceLoss,
  metrics: MicroIoU,
  optimizer: Adam,
  lr: 0.0001,
  scheduler: PolyLR,

}