{
  # Task Config
  do_train: true,
  do_test: true,
  output_dir: ../models,

  # Data Config   
  data_dir: ../data,
  train_file: train_drop.csv,
  num_workers: 4,

  # Model Config
  architecture: Unet,
  encoder_name: efficientnet-b1,
  encoder_weights: imagenet,
  classes: 1,
  activation: sigmoid,

  # Train Config
  epochs: 10,
  batch_size: 20,
  accumulation_steps: 4,
  verbose: true,

  losses: DiceLoss,
  metrics: MicroIoU,
  optimizer: Adam,
  lr: 0.0001,
  scheduler: PolyLR,
  train_transform: train_transform_2,
  test_transform: test_transform_1
}